### ISSUE TITLE
Find a way to adjust prochot or pbo scalar

### ISSUE THREAD

**Issue by Falcosc** [FlyGoat/ryzen_nb_smu#5]
I like to undervolt a bit with pbo scalar or try to adjust the extrem limit during prochot because PPT Slow and PPT settings are not good enough. 
I can't adjust the cooldown timer: time to wait until next boost is allowed, currently very little time without any load does allow way too much of my 30s boost time.
Which means the boost time is either to short for a cold CPU or is too long for a hot CPU.

> here's what I've started to document, although I have more commands as well (found mostly experimentally).
>
> https://docs.google.com/spreadsheets/d/15qC2GlLiF3gpW5d9pVMP4npJ14yDv_yP2zT6QGEWseg/edit?usp=sharing

_Originally posted by @irusanov in https://github.com/FlyGoat/ryzen_nb_smu/issues/3#issuecomment-622523999_

@irusanov based on this documentation you found prochot and pbo scalar adjustments.
I like to test them on renoir, but your values are looking odd.

For example your Picasso value have an offset of 0x13 to what I use to apply these values
And your Renoir values doesn't match my values at all.

Could you or somebody else describe what the difference between your values and the SMU Message Type Value is which I am using?

### Picasso seem to have offset of 0x13
| Command | google doc value | my value |
| --- | --- | --- |
| Set PPT Slow | 0x2F  | 0x1C |
| Set EDC | 0x35  | 0x22 |
| Set EDC SOC | 0x36  | 0x23 |
| GetPBOScalar | 0x62 | ? |
| SetPBOScalar | 0x7C | ? |

### Renoir doesn't align at all
| Command | google doc value | my value |
| --- | --- | --- |
| Set TDC | 0x3A  | 0x1A |
| Set TDC SOC | 0x3B  | 0x1B |
| Set EDC | 0x38  | 0x1C |
| Set EDC SOC | 0x37  | 0x1D |
| GetPBOScalar | 0xF | ? |
| SetPBOScalar | 0x3F | ? |
| IsDisableProcHOTAvailable | 0x8b | ? |
| DisablePROCHOT | 0x17 | ? |
| EnablePROCHOT| 0x18 | ? |

**Comment by irusanov** [comment]
Commands depend on the socket, I believe. Those listed on the spreadsheet are for the desktop variants.
Values for Renoir are mostly reverse-engineered and I haven't really tested them, because I don't have such CPU.
ZenTimings only uses 3-4 commands for getting table version, dram address and to update the power table and those seem to match for desktop and mobile SKUs.
Commands also depend on the SMU Mailbox used (RSMU, MP1). I'm currently only using one of them (RSMU), because I need a limited subset of features.

**Comment by Falcosc** [comment]
Do you have a Desktop Picasso? Or did somebody already prove some of your Desktop APU address findings?

If it is true that there are different addresses between Desktop and Mobile implementations of Picasso or Renoir, then we have to find a more sophisticated solution to determine the adjustment support. Because currently it is only checking CPU ID.

But if Mobile and Desktop addresses are equal for same CPU Designs, then you might have found something for the mobile people. We would just need to find out what did go wrong during the extraction of the addresses :)

Edit: found where you got the addresses from
https://github.com/FlyGoat/ryzen_nb_smu/issues/3#issuecomment-622486330
There are from ryzen master, that's enough of proof. Did you find the less important SoC limit by BIOS Reverse engineering or did you just try the Ids next to VDD messages out?

**Comment by Falcosc** [comment]
Already found the proof for different message Ids in your issue list. Some users did report that they have trouble using ryzen mobile with your tools.
Did you already found a sufficient solution to tell users about the non-supported platform? I didn't find commits about that after users did raise this issue last year.

Would be nice to adapt it in ryzenAdj because users on the same cpu design doesn't expect these incompatibilities.

If you didn't find a good distinction between the platforms I'm happy to provide you any reading you like to know.

By the way,  Renoir is `0x00860F10` I just found the issue where you get the Fenghuang CPU Id. I was surprised that you got it before Renoir :)
If I have a look on this list it does already tell that we have to consider other identifiers for msg support because desktop and mobile variants of the same cpu have the same id. 
https://fossies.org/linux/cpuid/cpuid.c

I hope it does not depend on the socket, but rather depends on the SMU version.
Did you have cases where 2 matching SMU versions across different sockets use different msg addresses?

**Comment by irusanov** [comment]
@Falcosc I have a desktop Picasso (3000G).
There are two variants of SMU firmware versions, however I don't know why.
One is in the form of `{0}.{1}.{2}.{3}` and the other - `{0}.{1}.{2}`, where each placeholder is a single byte and usually the least significant one is `00`.
I've had a case where another Picasso-based system had the first variant, where most of the desktop (if not all) have the second one. So I had to add some condition based on that:
https://github.com/irusanov/ZenStates-Core/blob/master/Cpu.cs#L534

I've also renamed the `Fenghuang` to `FireFlight`, which appears to be the official code name.
`Fenghuang` was reported long time ago from a Chinese user and it was even an ES CPU, that's why I have that in the code before even adding the newer ones. I believe this was some sort of a engineering code name.

The ZenStates Core project is the one I work mostly (used in ZenTimings) and ideally all my apps should use it at some point. I'm not really updating the rest of the projects at this point, but should get back to ZenStates sometime in the future.

Distinction by socket (package type) is possible, I already do it when detecting the codename.
Some SKUs share the same CPUID, but they have different codenames depending on the platform.
Package type is available from `0x80000001` CPUID instruction
https://github.com/irusanov/ZenStates-Core/blob/master/Cpu.cs#L154

I have switched from CPUID to model number, based on this wiki (and custom calculations for some of the CPUs): https://en.wikichip.org/wiki/amd/cpuid
Vermeer is wrong on that wiki.

To me, it seems there are several things it might depend on:
- SMU firmware version
- IF version (what IF decodes exactly to?) - this version is available from MP1 mailbox and has a command for it
- Socket
Power table version is another variable (available for read from the RSMU/PSMU mailbox), but it depends on the SMU version and the SKU.

Mailbox addresses seem to be the same for Mobile and Desktop, but I've mostly explored and used the RSMU mailbox, while this repo has the commands for the MP1. I can install the 3000G again and see if I can get some of the MP1 commands working.
Zen and Zen+ APUs seem to have the same commands and power table versions.

**Note**: Some of the commands you see on the spreadsheet are a **pure guess** based on known and proven command IDs for other SKUs, because they are usually in the same/similar order, but this doesn't mean they would work and can potentially be dangerous to try blindly. For the server SKUs most of them are guessed and/or reverse-engineered, but I don't have server platforms. I've tested some of them remotely or users have tested them for me, but there's nothing definitive and I'm really cautious with test on these expensive systems.

**Comment by Falcosc** [comment]
Thank you very much for your input. I will add at least basic distinctions to ryzenAdj to keep the desktop user from pocking their system with our mobile message ids.
And I did create an FAQ to redirect the Desktop users to you.

But maybe I add some of your temperature and power related desktop messages to ryzenAdj.
I did already steal your offset for the socket bits after failing at finding out where you get it from.

Do you remember about IF Version differences between `{0}.{1}.{2}.{3}` and `{0}.{1}.{2}` ? (Not important because I don't know what `SVI2` is)

Thanks for the Note, so then I will rely more on the Ryzen Master reverse engineer result.

I don't worry as much because ryzenAdj is currently online without blocking desktops at all and is only working on consumer plattforms.

By the way, I didn't see the leading `8` in the package type CPU ID parameter. Even worse, I did successfully test the wrong call with 0x1 because I got package type `0` which does acually match with FP6. This thing is just evil 😄

**Comment by Falcosc** [comment]
Wait a second, I guess I mixed things up.

Did you just tell me twice that your message ids are for RSMU and our message ids are for MP1?
Sorry, I'm still very new here. I don't even write C or C++ ;)

Could it be that we missed a lot of potential by only exploring MP1?
Maybe this does also mean that RSMU addresses could be equal for Mobile Picasso and Desktop Picasso, isn't it?
Or maybe MP1 message ids are equal between Mobile Picasso and Desktop Picasso.
These are our MP1 message ids https://github.com/FlyGoat/RyzenAdj/blob/master/lib/api.c

Your Renoir message Ids are correct. They match to my mobile Renoir. Maybe there is no difference between mobile and desktop?

Only `TDC LIMIT SOC` was wrong, it is on `0x39` instead of `0x37`

Here is the full test Result
```
0x32: PPT Limit Fast mW
0x33: PPT Limit Slow mW
0x3A: EDC LIMIT VDDD mA
0x3B: EDC LIMIT SOC mA
0x38: TDC LIMIT VDD mA
0x39: TDC LIMIT SOC mA

0x17: reject
0x18: ok
0x19: reject
0x1a: reject
0x82: isOverclockable result = 0
0xe: getAutoOverclockingGPU result 1600mhz
0x42: getAutoOvercklockingCPU result 4200mhz
0xF: getPBOScalar result = 0x3f800000
0x3F: rejected (0x3f800000, 0x3f700000, 0x3f700000, 0x1, 0x0)
```

Edit:
after reading the source thread a 3rd or even 4th time I do now start to understand things and feel so stupid to be the guy who did ask about miss matches between these message ids. I am sorry for wasting your time.
